### ISSUE TITLE
Move shiny app model parameters from sidebar to boxes on page 2

### ISSUE THREAD

**Issue by smjenness** [statnet/PrEPGuidelines#1]
I got the app to run by removing the `shiny/app/` references. If you need those to run on Windows for whatever reason (still odd to me), just use `setwd("path/to/app/")` since shinyapps.io will only recognize everything from `app/` upward.

Anyway, please move the parameter toggles from the sidebar to boxes on page 2, kind of like this app:
https://michaellevy.shinyapps.io/gwdegree/

**Comment by kweiss2** [comment]
Interesting, I thought I had taken those `shiny/app` references out on the new branch?

**Comment by smjenness** [comment]
I had a weird git merge issue (not related to anything you did), so I'm sure you did before but I had to do it on my end again. Github!
![GitHub](https://imgs.xkcd.com/comics/git.png)

**Comment by kweiss2** [comment]
Ah, ok! Updated version is on the branch

**Comment by kweiss2** [comment]
It still looks functional on my end, but trying to sync through GitHub produced an error message that said "Failed to sync branch: You might need to open a shell and debug the state of this repo."

**Comment by smjenness** [comment]
Ugh. I think you might have the follow the lead of the cartoon.

**Comment by kweiss2** [comment]
Are you seeing the same issue you had seen before then? I only hit "Sync" today

**Comment by smjenness** [comment]
It is sync'ing on my computer fine. Do you have any unsaved changed in the repo? If not, I recommend just deleting the folder and re-cloning the repository in the same place.

**Comment by kweiss2** [comment]
I re-cloned, will upload the changes momentarily

**Comment by kweiss2** [comment]
Ok, should be roughly the format it was in yesterday
